<?php
/*
Plugin Name: WPDR - AddOns
Plugin URI: https://github.com/benbalter/WP-Document-Revisions-Code-Cookbook
Description: All the Code Cookbook AddOns and Associated Configurations and Settings
	Other modifications to original programming have been made to increase modularity and functionality.
Version: 1.0
Author: Benjamin J. Balter & Michael R. Lewis
Author URI: https://github.com/benbalter/wp-document-revisions
Author URI2: https://github.com/benbalter/WP-Document-Revisions-Code-Cookbook
License: GPL2
*/
/**
To create admin settings pages:
 Admin Page Framework v3.5.6 by Michael Uno
 Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
 <http://en.michaeluno.jp/admin-page-framework>
 Copyright (c) 2013-2015, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT>
 Included Components: Admin Pages, Network Admin Pages, Custom Post Types, Taxonomy Fields, Post Meta Boxes, Page Meta Boxes, Widgets, User Meta, Utilities
 Generated on 2015-04-05 */
 
 
if ( !class_exists( 'appts_gf_AdminPageFramework' ) && is_admin()) :
	include_once( dirname( __FILE__ ) . '/WPDRAddOns/admin-framework/admin-page-framework.php' );
	if( !class_exists('WPDR_AddOns_Config') ) :
		class WPDR_AddOns_Config extends wpdr_AdminPageFramework {
			public function setUp(){
				$this->page_slug = 'wpdr';
				$this->setRootMenuPage( 'Settings' );        // specifies to which parent menu to add.
				$this->addSubMenuItems(
            array(
                'title'    =>    'Documents+',        // the page and menu title
                'page_slug'    =>  $this->page_slug           // the page slug
            )
        );
        $wpdr_forms = get_option('WPDR_AddOns_Config', array() );
				
				/*** Define Tab Here	***/
        $this->addInPageTabs(
            $this->page_slug,    // set the target page slug so that the 'page_slug' key can be omitted from the next continuing in-page tab arrays.
            array(
                'tab_slug'  =>    'wpdr_basic',    // avoid hyphen(dash), dots, and white spaces
                'title'     =>    __( 'Basic Addons', 'WPDRAddOns' ),
            )
        );
				
				/*** Define Sections Here ***/
				$this->addSettingSections(
			    $this->page_slug,
			    array(
		        'section_id' => 'opt',
		        'tab_slug' => 'wpdr_basic',
		        'title' => 'Options & Settings',
		        'description' => 'Additional taxonomy support.',
    			)
				);
				
				/***	Define Fields Here	***/
				$this->addSettingFields(
					'opt', //section_id for fields
       		array(
						'field_id'      => 'enable_file_type_taxonomy',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'checkbox',
						'title'         => __( 'Enable File Type Taxonomy', 'WPDRAddOns' ),
						'label'   => 'Adds support to filter by filetype.',
						'default'				=> false
      		),
      		array(
						'field_id'      => 'enable_taxonomy_permissions',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'checkbox',
						'title'         => __( 'Enable Taxonomy Permissions', 'WPDRAddOns' ),
						'label'   => 'Allows setting user-level permissions and access control based on document being in a given workflow state or other custom taxonomy such as department.',
						'default'				=> false
      		),
      		array(
						'field_id'      => 'enable_change_tracker',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'checkbox',
						'title'         => __( 'Enable Change Tracker', 'WPDRAddOns' ),
						'label'   => 'Auto-generates and appends revision summaries for changes to taxonomies, title, and visibility.',
						'default'				=> false
      		),
      		array(
						'field_id'      => 'enable_audit_trail',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'checkbox',
						'title'         => __( 'Enable Audit Trail', 'WPDRAddOns' ),
						'label'   => 'Creates check in / check out audit trail.',
						'default'				=> false
      		),
					array(
						'field_id'      => 'enable_forced_login',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'checkbox',
						'title'         => __( 'Force Login', 'WPDRAddOns' ),
						'label'   => 'Locks down site to non-logged in users.',
						'default'				=> false
      		),
					array(
						'field_id'      => 'remove_date_from_permalink',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'checkbox',
						'title'         => __( 'Remove Date from Permalinks', 'WPDRAddOns' ),
						'label'   => 'Remove the automatically prepended /yyyy/mm/ from document links.',
						'default'				=> false
      		),
					array(
						'field_id'      => 'remove_workflow_states',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'checkbox',
						'title'         => __( 'Remove Workflow State', 'WPDRAddOns' ),
						'label'   => 'Removes Workflow State Taxonomy from Documents.',
						'default'				=> false
      		),
      		array(
						'field_id'      => 'enable_queryable_workflow_state',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'checkbox',
						'title'         => __( 'Query By Workflow?', 'WPDRAddOns' ),
						'label'   => 'Makes workflow state front-end queryable. Only effective if workflow Taxonomy is not removed.',
						'default'				=> false
      		),
					array(
						'field_id'      => 'lock_extender',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'checkbox',
						'title'         => __( 'Extend Lock Buffer', 'WPDRAddOns' ),
						'label'   => 'Extends the default 2 minutes file lock buffer (how long a file is checked out if nothing is heard) to minutes entered below.',
						'default'				=> false
      		),
					array(
						'field_id'      => 'lock_extender_time',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'text',
						'title'         => __( 'Lock Buffer Time', 'WPDRAddOns' ),
						'description'   => 'In Minutes.',
						'default'				=> ''
      		),
					array(
						'field_id'      => 'document_parent',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'checkbox',
						'title'         => __( 'Document Parent', 'WPDRAddOns' ),
						'label'   => 'Creates UI for selecting document\'s post parent (useful for querying on the front-end like attachments).',
						'default'				=> false
      		),
					array(
						'field_id'      => 'rename_documents',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'checkbox',
						'title'         => __( 'Rename "Documents"', 'WPDRAddOns' ),
						'label'   => 'Changes all references to "Documents" in the interface to any label of your choosing.',
						'default'				=> false
      		),
					array(
						'field_id'      => 'rename_documents_label',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'text',
						'title'         => __( 'Singular Label', 'WPDRAddOns' ),
						'description'   => 'What do you want to label a "Document" as now?.',
						'default'				=> 'Document'
      		),
					array(
						'field_id'      => 'rename_documents_label_plural',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'text',
						'title'         => __( 'Plural Label', 'WPDRAddOns' ),
						'description'   => 'What do you want to label "Documents" as now?.',
						'default'				=> 'Documents'
      		),
					array(
						'field_id'      => 'hide_rss_key_in_profile',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'checkbox',
						'title'         => __( 'Hide RSS Key in User Profile', 'WPDRAddOns' ),
						'label'   => 'IF you are tired of explaining what this is...',
						'default'				=> false
      		),
					array(
						'field_id'      => 'remove_post_lock_override',
						'tab_slug'      => 'wpdr_basic',
						'type'          => 'checkbox',
						'title'         => __( 'Remove Post Lock Override', 'WPDRAddOns' ),
						'label'   => 'If you have a problem with people overriding other people\'s document locks.',
						'default'				=> false
      		),
      		
          array(
            'field_id' => 'submit_button',
            'type' => 'submit'
          )
        );
				$this->setPageHeadingTabsVisibility( false );    // disables the page heading tabs by passing false.
        $this->setInPageTabTag( 'h2' );
			}//end setup
		}
		new WPDR_AddOns_Config;
	endif; //class_exists( 'WPDR_AddOns_Config' )
endif;//class_exists( 'wpdr_AdminPageFramework' )


if(!class_exists('load_wpdr_addons')):
  class load_wpdr_addons {
  	public function load_wpdr_addons(){
  		global $wpdr;
			$admin = $wpdr->admin;
			
			//uncomment if you want to remove the network admin settings (alternate file locations and such
			remove_action( 'wpmu_options', array( &$admin, 'network_settings_cb' ) );
			
  		if($options = get_option('WPDR_AddOns_Config', false)){
  			if( $options['opt']['enable_file_type_taxonomy'] )
  				include 'WPDRAddOns/filetype-filter.php';
  			if( $options['opt']['enable_taxonomy_permissions'] )
  				include 'WPDRAddOns/taxonomy-permissions.php';
				if( $options['opt']['enable_change_tracker'] )
  				include 'WPDRAddOns/change-tracker.php';
  			if( $options['opt']['enable_audit_trail'] )
  				include 'WPDRAddOns/audit-trail.php';
				if( $options['opt']['remove_date_from_permalink'] )
  				include 'WPDRAddOns/remove-date-from-permalink.php';
  			if( $options['opt']['enable_forced_login'] )
  				include 'WPDRAddOns/force-login.php';
  			if( $options['opt']['remove_workflow_states'] )
  				include 'WPDRAddOns/remove-workflow-states.php';
  			if( $options['opt']['lock_extender'] )
  				include 'WPDRAddOns/pclj-lock-extender.php';
  			if( $options['opt']['document_parent'] )
  				include 'WPDRAddOns/document-parent/document-post-parent.php';
  			if( $options['opt']['rename_documents'] )
  				include 'WPDRAddOns/rename-documents.php';
  			if( $options['opt']['enable_queryable_workflow_state'] )
  				include 'WPDRAddOns/pclj-make-workflow-state-queryable.php';
  			if( $options['opt']['hide_rss_key_in_profile'] )
					remove_action( 'show_user_profile', array( $admin, 'rss_key_display' ) );
  			if( $options['opt']['remove_post_lock_override'] )
  				add_filter( 'override_post_lock', create_function("", 'return false;' ));
  		}
  	}
	}
	new load_wpdr_addons;
endif;//class_exists('load_wpdr_addons')
?>